58, Night Safari, Family, page: None, None, 2020-01-28 15:19:42.852916
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:20:49.482268
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 194, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:21:00.879330
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:21:14.522776
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:21:25.172564
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:21:37.607775
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 6, 2019-10-08 00:00:00, 2020-01-28 15:21:49.680018
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 16, 2019-06-29 00:00:00, 2020-01-28 15:23:35.462013
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 194, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 16, 2019-06-29 00:00:00, 2020-01-28 15:23:47.002853
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-tracker="Family"]"}
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 16, 2019-06-29 00:00:00, 2020-01-28 15:24:09.715338
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 183, in crawl_poi_by_trip_type
    self.crawl_reviews()
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 309, in crawl_reviews
    self.crawl_reviews_1_page(self.current_poi_index)
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 340, in crawl_reviews_1_page
    review_more_buttons[0].click()
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="taLnk ulBlueLinks" onclick="widgetEvCall('handlers.clickExpand',event,this);">...</span> is not clickable at point (639, 8). Other element would receive the click: <a class="attractions-ar-persistent-header-PivotLink__link--3ef4y attractions-ar-persistent-header-PivotLink__white_background--G_NTm" href="/Attractions-g294265-Activities-Singapore.html">...</a>
  (Session info: chrome=79.0.3945.130)


58, Night Safari, Family, page: 16, 2019-06-29 00:00:00, 2020-01-28 15:24:20.266056
Traceback (most recent call last):
  File "/home/zyf0717/git_environment/STB_social_media_analytics/tripadvisor/tripadvisor_crawler_v2.py", line 161, in crawl_poi_by_trip_type
    '//div[@data-tracker="{}"]'.format(self.current_trip_type))
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zyf0717/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=79.0.3945.130)


